const DEFAULT_PRODUCTS=[
{id:1,name:"Classic Denim Jacket",category:"Fashion",price:1899,old:2999,rating:4.5,image:"https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=700&q=80",description:"A versatile denim jacket with a timeless fit for everyday wear."},
{id:2,name:"Minimal Sneakers",category:"Fashion",price:1499,old:2499,rating:4.4,image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80",description:"Comfortable everyday sneakers designed for casual outfits and long walks."},
{id:3,name:"Smart Watch Pro",category:"Electronics",price:3999,old:5999,rating:4.6,image:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80",description:"Fitness tracking, notifications and a bright display in a sleek smartwatch."},
{id:4,name:"Wireless Headphones",category:"Electronics",price:2499,old:3999,rating:4.7,image:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=80",description:"Rich sound and comfortable ear cushions for music, calls and travel."},
{id:5,name:"Coffee Maker",category:"Home",price:3299,old:4499,rating:4.3,image:"https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=700&q=80",description:"Easy-to-use coffee maker for delicious coffee at home."},
{id:6,name:"Modern Table Lamp",category:"Home",price:999,old:1499,rating:4.2,image:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80",description:"Warm ambient lighting with a clean modern design."},
{id:7,name:"Skincare Essentials Set",category:"Beauty",price:799,old:1199,rating:4.5,image:"https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=700&q=80",description:"A simple daily skincare set for a fresh and healthy-looking routine."},
{id:8,name:"Everyday Makeup Kit",category:"Beauty",price:1299,old:1999,rating:4.4,image:"https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=700&q=80",description:"A compact collection of makeup essentials for everyday looks."}
];

function getProducts(){let p=JSON.parse(localStorage.getItem("stylenest_products"));if(!p){localStorage.setItem("stylenest_products",JSON.stringify(DEFAULT_PRODUCTS));return DEFAULT_PRODUCTS}return p}
function saveProducts(p){localStorage.setItem("stylenest_products",JSON.stringify(p))}
function getCart(){return JSON.parse(localStorage.getItem("stylenest_cart")||"[]")}
function saveCart(c){localStorage.setItem("stylenest_cart",JSON.stringify(c));updateCartCount()}
function getWishlist(){return JSON.parse(localStorage.getItem("stylenest_wishlist")||"[]")}
function saveWishlist(w){localStorage.setItem("stylenest_wishlist",JSON.stringify(w))}
function money(n){return "₹"+Number(n).toLocaleString("en-IN")}
function stars(r){return `<span class="rating">${"★".repeat(Math.round(r))}${"☆".repeat(5-Math.round(r))}</span> <small>${r}</small>`}
function toast(msg){let x=document.createElement("div");x.className="toast";x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}

function header(){
document.getElementById("header").innerHTML=`<header>
<div class="top">
<a class="logo" href="index.html">Style<span>Nest</span></a>
<div class="deliver">📍 <small>Deliver to</small><b>India</b></div>
<div class="search"><select id="search-cat"><option>All</option><option>Fashion</option><option>Electronics</option><option>Home</option><option>Beauty</option></select><input id="search-box" placeholder="Search StyleNest"><button onclick="doSearch()">🔍</button></div>
<a class="head-link" href="login.html"><small>Hello, sign in</small><b>Account & Lists ▾</b></a>
<a class="head-link" href="orders.html"><small>Returns</small><b>& Orders</b></a>
<a class="cart-link" href="cart.html">🛒 <span class="cart-count" id="cart-count">0</span> Cart</a>
</div>
<nav class="nav"><a href="products.html">☰ All</a><a href="index.html">Home</a><a href="products.html">Today's Deals</a><a href="products.html">Best Sellers</a><a href="products.html?category=Fashion">Fashion</a><a href="products.html?category=Electronics">Electronics</a><a href="products.html?category=Home">Home</a><a href="products.html?category=Beauty">Beauty</a><a class="owner" href="owner.html">👑 Owner</a></nav>
</header>`;
updateCartCount();
document.getElementById("search-box").addEventListener("keydown",e=>{if(e.key==="Enter")doSearch()})
}
function footer(){let f=document.getElementById("footer");if(f)f.innerHTML=`<footer><div class="footer-top" onclick="window.scrollTo({top:0,behavior:'smooth'})">Back to top</div><div class="footer"><div class="footer-grid"><div><h3>Get to Know Us</h3><p>About StyleNest</p><p>Careers</p><p>Press Releases</p></div><div><h3>Make Money with Us</h3><p>Sell on StyleNest</p><p>Become an Affiliate</p><p>Advertise Products</p></div><div><h3>Customer Service</h3><p>Your Account</p><p>Returns Centre</p><p>Help</p></div><div><h3>Let Us Help You</h3><p>Shipping Rates</p><p>Privacy</p><p>Terms & Conditions</p></div></div><div class="footer-bottom">StyleNest</div></div></footer>`}
function updateCartCount(){let el=document.getElementById("cart-count");if(el)el.textContent=getCart().reduce((s,x)=>s+x.qty,0)}
function doSearch(){let q=document.getElementById("search-box").value.trim();let cat=document.getElementById("search-cat").value;if(!q&&cat==="All"){location.href="products.html";return}location.href=`products.html?search=${encodeURIComponent(q)}&category=${encodeURIComponent(cat)}`}
function card(p){let wished=getWishlist().includes(p.id);return `<article class="product-card"><button class="wish" onclick="toggleWish(${p.id})">${wished?"♥":"♡"}</button><a href="product-details.html?id=${p.id}"><img src="${p.image}" alt="${p.name}"></a><h3><a href="product-details.html?id=${p.id}">${p.name}</a></h3><div>${stars(p.rating)}</div><div><span class="badge">Deal</span></div><div class="price">${money(p.price)} <span class="old">${money(p.old)}</span></div><small>${p.description}</small><div class="card-actions"><button class="btn" onclick="addCart(${p.id})">Add to Cart</button><button class="btn orange" onclick="buyNow(${p.id})">Buy Now</button></div></article>`}
function addCart(id){let p=getProducts().find(x=>x.id===id);let c=getCart(),i=c.findIndex(x=>x.id===id);if(i>=0)c[i].qty++;else c.push({id,qty:1});saveCart(c);toast(p.name+" added to cart")}
function buyNow(id){addCart(id);location.href="cart.html"}
function toggleWish(id){let w=getWishlist(),i=w.indexOf(id);if(i>=0){w.splice(i,1);toast("Removed from wishlist")}else{w.push(id);toast("Added to wishlist")}saveWishlist(w);refreshCurrentPage()}
function renderProductsIfPresent(){let el=document.getElementById("product-grid");if(!el)return;let ps=getProducts();let params=new URLSearchParams(location.search),q=(params.get("search")||"").toLowerCase(),cat=params.get("category")||"All";let selected=document.querySelector('input[name="cat"]:checked')?.value||cat;cat=selected;if(cat!=="All")ps=ps.filter(p=>p.category.toLowerCase()===cat.toLowerCase());if(q)ps=ps.filter(p=>(p.name+" "+p.description+" "+p.category).toLowerCase().includes(q));let price=document.querySelector('input[name="price"]:checked')?.value||"all";if(price==="low")ps=ps.filter(p=>p.price<1000);if(price==="mid")ps=ps.filter(p=>p.price>=1000&&p.price<=5000);if(price==="high")ps=ps.filter(p=>p.price>5000);let sort=document.getElementById("sort")?.value;if(sort==="low")ps.sort((a,b)=>a.price-b.price);if(sort==="high")ps.sort((a,b)=>b.price-a.price);if(sort==="rating")ps.sort((a,b)=>b.rating-a.rating);document.getElementById("results-title").textContent=q?`Search results for "${q}"`:cat==="All"?"All Products":cat;document.getElementById("results-count").textContent=`${ps.length} results`;el.innerHTML=ps.length?ps.map(card).join(""):`<div class="empty">No products found. Try another search.</div>`}
function initProducts(){let params=new URLSearchParams(location.search),cat=params.get("category")||"All";let radio=document.querySelector(`input[name="cat"][value="${cat}"]`);if(radio)radio.checked=true;document.querySelectorAll('input[name="cat"],input[name="price"]').forEach(x=>x.addEventListener("change",renderProductsIfPresent));document.getElementById("sort").addEventListener("change",renderProductsIfPresent);renderProductsIfPresent()}
function renderDeals(){let el=document.getElementById("deal-products");if(el)el.innerHTML=getProducts().slice(0,4).map(card).join("")}
function initDetail(){let id=Number(new URLSearchParams(location.search).get("id"));let p=getProducts().find(x=>x.id===id),el=document.getElementById("detail");if(!p){el.innerHTML="<div class='empty'>Product not found.</div>";return}el.innerHTML=`<div class="detail"><div><img src="${p.image}" alt="${p.name}"></div><div><div class="breadcrumb">StyleNest › ${p.category}</div><h1>${p.name}</h1>${stars(p.rating)}<hr><p>Deal price</p><div class="detail-price">${money(p.price)} <span class="old">${money(p.old)}</span></div><p>${p.description}</p><p>✓ FREE delivery on eligible orders<br>✓ Secure payment<br>✓ 7-day easy returns</p><div class="card-actions"><button class="btn" onclick="addCart(${p.id})">Add to Cart</button><button class="btn orange" onclick="buyNow(${p.id})">Buy Now</button></div></div><div class="reviews"><h2>Customer reviews</h2><div class="review">${stars(p.rating)}<br>Great product and good value for money.</div><div class="review">${stars(Math.max(4,p.rating-.2))}<br>Looks exactly as shown and arrived safely.</div></div></div>`}
function initCart(){let el=document.getElementById("cart-items"),sum=document.getElementById("cart-summary"),c=getCart(),ps=getProducts();if(!c.length){el.innerHTML="<div class='empty'><h2>Your StyleNest Cart is empty</h2><p>Shop today's deals and discover something you love.</p><a class='btn yellow' href='products.html'>Continue shopping</a></div>";sum.innerHTML="";return}let rows=c.map(x=>{let p=ps.find(z=>z.id===x.id);return `<div class="cart-row"><img src="${p.image}"><div><h3><a href="product-details.html?id=${p.id}">${p.name}</a></h3><div>${stars(p.rating)}</div><div class="price">${money(p.price)}</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${x.qty}</b><button onclick="changeQty(${p.id},1)">+</button><button class="danger" onclick="removeCart(${p.id})">Delete</button></div></div></div>`}).join("");el.innerHTML=rows;let total=c.reduce((s,x)=>s+ps.find(p=>p.id===x.id).price*x.qty,0),count=c.reduce((s,x)=>s+x.qty,0);sum.innerHTML=`<aside class="summary"><h2>Subtotal (${count} items)</h2><div class="total">${money(total)}</div><p>FREE delivery available</p><button class="btn yellow full" onclick="placeOrder()">Proceed to Buy</button></aside>`}
function changeQty(id,n){let c=getCart(),x=c.find(z=>z.id===id);x.qty+=n;if(x.qty<=0)c=c.filter(z=>z.id!==id);saveCart(c);initCart()}
function removeCart(id){saveCart(getCart().filter(x=>x.id!==id));initCart();toast("Item removed")}
function placeOrder(){if(!getCart().length)return;let orders=JSON.parse(localStorage.getItem("stylenest_orders")||"[]"),c=getCart(),ps=getProducts();orders.unshift({id:"SN"+Date.now(),date:new Date().toLocaleString("en-IN"),items:c.map(x=>{let p=ps.find(z=>z.id===x.id);return {name:p.name,image:p.image,qty:x.qty,price:p.price}})});localStorage.setItem("stylenest_orders",JSON.stringify(orders));saveCart([]);toast("Order placed successfully");setTimeout(()=>location.href="orders.html",700)}
function initWishlist(){let el=document.getElementById("wishlist-grid"),w=getWishlist(),ps=getProducts().filter(p=>w.includes(p.id));el.innerHTML=ps.length?ps.map(card).join(""):`<div class="empty">Your wishlist is empty.<br><br><a class="btn yellow" href="products.html">Explore products</a></div>`}
function initOrders(){let el=document.getElementById("orders"),o=JSON.parse(localStorage.getItem("stylenest_orders")||"[]");el.innerHTML=o.length?o.map(x=>`<div class="order"><div class="order-head"><b>Order #${x.id}</b><span>${x.date}</span></div>${x.items.map(i=>`<div class="cart-row"><img src="${i.image}"><div><h3>${i.name}</h3><p>Quantity: ${i.qty}</p><b>${money(i.price*i.qty)}</b></div></div>`).join("")}</div>`).join(""):`<div class="empty"><h2>You haven't placed any orders yet.</h2><a class="btn yellow" href="products.html">Start shopping</a></div>`}
function login(){let e=document.getElementById("email").value.trim(),p=document.getElementById("password").value;if(e==="owner@stylenest.com"&&p==="Owner@123"){localStorage.setItem("stylenest_user","owner");location.href="owner.html"}else if(e&&p){localStorage.setItem("stylenest_user","customer");location.href="index.html"}else document.getElementById("login-message").textContent="Please enter email and password."}
function logout(){localStorage.removeItem("stylenest_user");toast("Signed out");setTimeout(()=>location.reload(),400)}
function isOwner(){return localStorage.getItem("stylenest_user")==="owner"}
function initAccount(){let e=document.getElementById("account-status");if(e)e.textContent=isOwner()?"Signed in as Owner":"You can sign in to your account."}
function initOwner(){let locked=document.getElementById("owner-locked"),content=document.getElementById("owner-content");if(!isOwner()){locked.innerHTML=`<b>Owner access only.</b> Please <a href="login.html">sign in with the owner account</a> to manage products.`;return}locked.style.display="none";content.style.display="block";renderOwnerProducts()}
function renderOwnerProducts(){let el=document.getElementById("owner-products");if(!el)return;el.innerHTML=getProducts().map(p=>`<tr><td>${p.name}</td><td>${p.category}</td><td>${money(p.price)}</td><td><button class="btn small" onclick="editProduct(${p.id})">Edit</button> <button class="danger" onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join("")}
function saveProduct(){if(!isOwner())return;let id=Number(document.getElementById("edit-id").value),p={id:id||Date.now(),name:document.getElementById("p-name").value.trim(),price:Number(document.getElementById("p-price").value),old:Number(document.getElementById("p-old").value)||0,category:document.getElementById("p-category").value.trim()||"Fashion",image:document.getElementById("p-image").value.trim()||"https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=700&q=80",rating:Number(document.getElementById("p-rating").value)||4.5,description:document.getElementById("p-description").value.trim()||"A quality product from StyleNest."};if(!p.name||!p.price){toast("Enter product name and price");return}let ps=getProducts(),i=ps.findIndex(x=>x.id===id);if(i>=0)ps[i]=p;else ps.unshift(p);saveProducts(ps);clearForm();renderOwnerProducts();toast(i>=0?"Product updated":"Product added")}
function editProduct(id){let p=getProducts().find(x=>x.id===id);document.getElementById("edit-id").value=p.id;document.getElementById("p-name").value=p.name;document.getElementById("p-price").value=p.price;document.getElementById("p-old").value=p.old;document.getElementById("p-category").value=p.category;document.getElementById("p-image").value=p.image;document.getElementById("p-rating").value=p.rating;document.getElementById("p-description").value=p.description;document.getElementById("form-title").textContent="Edit Product";window.scrollTo({top:0,behavior:"smooth"})}
function clearForm(){["edit-id","p-name","p-price","p-old","p-category","p-image","p-rating","p-description"].forEach(id=>document.getElementById(id).value="");document.getElementById("form-title").textContent="Add New Product"}
function deleteProduct(id){if(!isOwner())return;if(confirm("Delete this product?")){saveProducts(getProducts().filter(p=>p.id!==id));renderOwnerProducts();toast("Product deleted")}}
function refreshCurrentPage(){if(document.getElementById('product-grid'))initProducts();if(document.getElementById('deal-products'))renderDeals();if(document.getElementById('wishlist-grid'))initWishlist()}

document.addEventListener("DOMContentLoaded",()=>{
if(document.getElementById("header"))header();if(document.getElementById("footer"))footer();
if(document.getElementById("deal-products"))renderDeals();
if(document.getElementById("product-grid"))initProducts();
if(document.getElementById("detail"))initDetail();
if(document.getElementById("cart-items"))initCart();
if(document.getElementById("wishlist-grid"))initWishlist();
if(document.getElementById("orders"))initOrders();
if(document.getElementById("account-status"))initAccount();
if(document.getElementById("owner-content"))initOwner();
});
